#!/usr/bin/env python3
"""
Seymour Wins — DAILY CONSTANTS BUILDER
Generates daily_constants.json: 100 things that happen EVERY day, everywhere,
as the structural substrate for the memetic-overlap timeline.

Each constant is a vertical thread (like a calendar date) that the user's
stream transcripts ("meme transcripts of my streams") overlap onto — the
Cambrian explosion of memetic overlap information.

Run:  python3 build_constants.py   -> writes ponderables/daily_constants.json
"""
import json, os

ROOT = "/home/wubu/seymour-project"
OUT = f"{ROOT}/ponderables/daily_constants.json"

# (name, category, theme[clipart], stream_link, universal, overlap, instance)
# theme in: penny, supercap, versa, gaming, cuda, internet, paulsen, meme
# stream_link in: gaming_stream, drive_commute, daily_life, night_think, all
BASE = [
    # ---- COSMIC / NATURAL (DC001-DC020) ----
    ("Sunrise", "cosmic", "paulsen", "drive_commute", True,
     "Same sun every human day since forever; the constant thread through all 'through the years' columns.",
     "6:14am, red line over the highway you commute."),
    ("Sunset", "cosmic", "paulsen", "daily_life", True,
     "The day's hard stop. Every civilization built a ritual around this constant.",
     "8:47pm, the sky goes copper while the stream is still live."),
    ("Earth rotates (day/night)", "cosmic", "paulsen", "all", True,
     "The master clock. Every other daily constant is a child of this one.",
     "You feel it as the commute home, the body winding down."),
    ("Moon shifts phase", "cosmic", "paulsen", "night_think", True,
     "Slow daily drift; the only constant you can watch change shape.",
     "A thin crescent over the Versa's hood at 11pm."),
    ("Tides rise and fall", "cosmic", "versa", "daily_life", True,
     "The moon's grip on water; a clock older than any government.",
     "Harbor tide gauge flips at 3am, nobody watching but the sensor."),
    ("Stars appear (night side)", "cosmic", "paulsen", "night_think", True,
     "Half the planet sees them every night; the other half never does.",
     "Orion over the commute, same as your dad saw."),
    ("Solar wind hits magnetosphere", "cosmic", "cuda", "all", True,
     "A constant weather from the sun; auroras are its visible mood.",
     "Quiet particle rain; your router doesn't care."),
    ("Photosynthesis runs", "cosmic", "paulsen", "daily_life", True,
     "Every green leaf is a daily factory converting light to sugar.",
     "The tree outside the window does it while you sleep."),
    ("Rain falls somewhere", "cosmic", "versa", "daily_life", True,
     "The planet never stops watering itself; someone is always getting wet.",
     "Windshield wipers on the Versa, a different city's drought."),
    ("Wind blows", "cosmic", "versa", "daily_life", True,
     "Air is never still; the atmosphere is always redistributing itself.",
     "A gust rocks the car at the gas pump."),
    ("Ocean currents move", "cosmic", "versa", "all", True,
     "Slow rivers in the sea; the planet's radiator, running daily.",
     "Gulf Stream pushes warm water north while you idle in traffic."),
    ("A volcano erupts", "cosmic", "paulsen", "all", False,
     "Statistically, ~40 eruptions are active on any given day somewhere.",
     "A mountain in Indonesia exhales; news feed skips it."),
    ("An earthquake shakes", "cosmic", "paulsen", "all", False,
     "The planet cracks daily — several hundred felt quakes per day globally.",
     "A 4.2 under Turkey while you're mid-stream."),
    ("A meteor burns up", "cosmic", "cuda", "night_think", True,
     "~25 million meteoroids enter daily; most burn unseen.",
     "A streak over the roof, gone before you look up."),
    ("Trees add a ring of cells", "cosmic", "paulsen", "daily_life", True,
     "Growth is a daily accretion; the forest is a slow ledger.",
     "The backyard oak widened by microns today."),
    ("Bacteria divide", "cosmic", "cuda", "all", True,
     "Life's fastest clock; a colony doubles while you read this.",
     "In your gut, in the sink, everywhere, right now."),
    ("Birds begin migration flight", "cosmic", "paulsen", "drive_commute", True,
     "Seasonal but daily movement; the original commute, older than roads.",
     "Geese V over the freeway at dawn."),
    ("Aurora flickers at the poles", "cosmic", "cuda", "night_think", True,
     "Solar wind made visible; the planet's daily light show for no one.",
     "Green curtains over Norway; you're asleep."),
    ("Cosmic background bathes Earth", "cosmic", "cuda", "all", True,
     "The echo of the Big Bang lands on you every second of every day.",
     "13.8B-year-old static, through the wall, through you."),
    ("A glacier calves", "cosmic", "paulsen", "all", False,
     "Ice sheets shed daily; the slowest daily constant on the list.",
     "A slab the size of a building drops in Antarctica."),

    # ---- BODY / BIOLOGICAL (DC021-DC040) ----
    ("Heart beats", "body", "supercap", "all", True,
     "~100,000 beats/day; the most reliable machine you own.",
     "Lub-dub through the whole stream, never off-shift."),
    ("Breath in and out", "body", "supercap", "all", True,
     "~20,000 breaths/day; the only constant you can choose to stop.",
     "In on the headshot, out on the respawn."),
    ("Cells die and replace", "body", "meme", "all", True,
     "You are not the same body as yesterday; replacement is daily.",
     "Skin sheds while you grind a rank."),
    ("A dream occurs (REM)", "body", "night_think", "night_think", True,
     "The brain runs its own stream nightly; the original 'content'.",
     "You were in a city that doesn't exist, then woke to this one."),
    ("Eyes blink", "body", "meme", "all", True,
     "~15,000 blinks/day; micro-blackouts you consent to.",
     "Blink during a clutch moment, miss nothing, trust the buffer."),
    ("Hair and skin shed", "body", "paulsen", "daily_life", True,
     "The body is a slow fountain; you leave yourself everywhere.",
     "A hair on the controller, one more for the collection."),
    ("Gut bacteria digest", "body", "cuda", "all", True,
     "Trillions of tenants run the daily chemistry you take credit for.",
     "They process the gas-station taquito; you take the win."),
    ("Neurons fire", "body", "cuda", "all", True,
     "~billions of spikes/day; thought is just weather in the skull.",
     "A synapse fires the moment you decide to push forward."),
    ("Blood circulates", "body", "supercap", "all", True,
     "The delivery network never clocks out; ~7,500L/day round-trip.",
     "Oxygen reaches your fingers mid-keyboard, on schedule."),
    ("Immune system patrols", "body", "cuda", "all", True,
     "A daily silent war; most battles you never feel.",
     "A cold virus stopped at the border while you raged at lag."),
    ("Sleep cycle runs", "body", "night_think", "night_think", True,
     "The reset; the one daily constant capitalism fights and loses.",
     "You crash at 1am, stream still queued in your head."),
    ("Hunger signals", "body", "penny", "daily_life", True,
     "The body's daily invoice; eat or the system throttles.",
     "Stomach at 3pm, exactly when the raid starts."),
    ("Thirst signals", "body", "supercap", "daily_life", True,
     "The water ledger; a daily reminder you are mostly ocean.",
     "Reach for the bottle mid-stream, never break eye contact."),
    ("Body temperature cycles", "body", "supercap", "all", True,
     "Circadian thermal tide; you run ~1C cooler at 4am.",
     "The apartment feels colder exactly when the night think hits."),
    ("Melatonin rises at night", "body", "night_think", "night_think", True,
     "The chemical curtain; the body's daily 'go offline' signal.",
     "Eyes heavy at midnight, but the stream isn't done."),
    ("Cortisol peaks at waking", "body", "meme", "drive_commute", True,
     "The stress hormone's dawn spike; evolution's alarm clock.",
     "Jolt awake at 6am, already calculating the commute cost."),
    ("Tears are made", "body", "meme", "all", True,
     "The eye's daily rinse; grief and onions both trigger it.",
     "A stupid loss in ranked, a blink, clear again."),
    ("Skin regenerates", "body", "paulsen", "daily_life", True,
     "A new outer you every ~27 days; the daily version is a draft.",
     "The callus on your thumb from the controller, thickening."),
    ("Vocal cords vibrate", "body", "meme", "gaming_stream", True,
     "Speech is a daily instrument; you tune it without thinking.",
     "You narrate the play-by-play; the stream hears you."),
    ("Pupils dilate and contract", "body", "cuda", "all", True,
     "The eye's daily aperture; attention made visible.",
     "Pupils blow open at the jump-scare, close at the menu."),

    # ---- SOCIAL / BEHAVIORAL (DC041-DC060) ----
    ("Someone commutes", "social", "versa", "drive_commute", True,
     "Billions of daily transits; the commute is the modern wilderness.",
     "You, 1.5h each way, the Versa, the thinking space."),
    ("A meal is eaten", "social", "penny", "daily_life", True,
     "~3 meals/person/day; the most universal daily ritual.",
     "Breakfast before stream, dinner after, both at the desk."),
    ("Money changes hands", "social", "penny", "daily_life", True,
     "Trillions of daily transactions; trust quantized into tokens.",
     "You buy the game, the mic, the sub — pennies compounding."),
    ("A conversation happens", "social", "meme", "all", True,
     "Language is the original meme medium; it runs constantly.",
     "You talk to chat, to yourself, to the game."),
    ("A baby is born", "social", "meme", "all", False,
     "~385,000 births/day globally; the daily reset of the species.",
     "Somewhere a clock starts the same minute yours ends a stream."),
    ("A person dies", "social", "meme", "all", False,
     "~170,000 deaths/day; the constant the news hides in aggregates.",
     "A name becomes a number while you laugh at a clip."),
    ("Someone falls in love", "social", "meme", "all", True,
     "The daily miracle; a brain rewires around another brain.",
     "A viewer meets a viewer in chat; lore is born."),
    ("An argument occurs", "social", "meme", "gaming_stream", True,
     "Conflict is how groups negotiate; it's daily and ancient.",
     "Flame war in chat, you mute, the meme spreads anyway."),
    ("Laughter happens", "social", "meme", "gaming_stream", True,
     "The social signal of 'we're safe'; ~15 laughs/day per person.",
     "Chat says something dumb, you lose it on stream."),
    ("Someone cries", "social", "meme", "all", True,
     "The pressure valve; grief and relief share the same outlet.",
     "Off-stream, a hard day, the same eyes that read chat."),
    ("A phone is checked", "social", "internet", "all", True,
     "~58 checks/person/day; the daily totem of the connected.",
     "You glance at the second monitor mid-load screen."),
    ("An email is sent", "social", "internet", "daily_life", True,
     "~330B emails/day; the background hum of obligation.",
     "A confirmation lands while you're live; ignored."),
    ("News is consumed", "social", "internet", "all", True,
     "The daily briefing reflex; the fossil record everyone skims.",
     "You scroll the headline, file it, keep streaming."),
    ("An ad is seen", "social", "internet", "all", True,
     "~5,000 ad impressions/person/day; the constant sell.",
     "Pre-roll before the video, skipped in 5 seconds."),
    ("A lie is told", "social", "meme", "all", True,
     "Deception is a daily social tool; the meme that predates writing.",
     "Someone in chat claims a clip; you fact-check live."),
    ("A promise is made", "social", "meme", "all", True,
     "The future contracted daily; most quietly expire.",
     "You promise chat 'one more game' — the tenth time."),
    ("Strangers pass unspeaking", "social", "versa", "drive_commute", True,
     "The daily silence of the crowd; proximity without contact.",
     "Cars in the next lane, faces lit by dashboards."),
    ("A queue forms", "social", "versa", "daily_life", True,
     "Waiting is a daily tax; lines are how scarcity is rationed.",
     "Drive-thru line, the 4th car back, phone in hand."),
    ("A decision is made", "social", "meme", "all", True,
     "~35,000 decisions/day; choice is the species' native state.",
     "Push or retreat — decided in 200ms, the whole game in that."),
    ("A habit is performed", "social", "meme", "all", True,
     "The autopilot self; most of the day is a remembered script.",
     "You boot the PC, launch the game, same as yesterday."),

    # ---- DIGITAL / INFO (DC061-DC075) ----
    ("A data packet is routed", "digital", "cuda", "all", True,
     "The planet's nervous system fires constantly; you ride it blind.",
     "Your voice to chat, 12 hops in 40ms."),
    ("A search is queried", "digital", "internet", "all", True,
     "~8.5B searches/day; the daily urge to know, outsourced.",
     "You Google a strat mid-stream, alt-tab fluid."),
    ("A meme is shared", "digital", "meme", "gaming_stream", True,
     "The unit of cultural replication; the project's namesake act.",
     "Chat spawns a meme from your fail; it leaves the stream."),
    ("A video is uploaded", "digital", "internet", "gaming_stream", True,
     "~500hrs/min uploaded to YouTube alone; the daily flood.",
     "Your stream's VOD joins the pile, timestamped forever."),
    ("Code is deployed", "digital", "cuda", "all", True,
     "Software ships daily; the world recompiles while you sleep.",
     "A patch drops, your game changes, you adapt live."),
    ("An AI inference runs", "digital", "cuda", "all", True,
     "Billions of model calls/day; thought, industrialized.",
     "The recommender picks your next video before you click."),
    ("A bot crawls the web", "digital", "internet", "all", True,
     "Non-human readers outnumber human ones; the archive is automatic.",
     "A crawler snapshots your stream page; you'll never meet it."),
    ("A password is entered", "digital", "cuda", "all", True,
     "The daily key-ritual; identity reduced to a typed spell.",
     "You log in, the gate opens, the session begins."),
    ("A notification fires", "digital", "internet", "all", True,
     "~60-80 notifications/day/person; the leash tugs constantly.",
     "Ping mid-stream; you don't look; the phone knows."),
    ("A stream goes live", "digital", "gaming_stream", "gaming_stream", True,
     "Thousands of live streams at any second; the project's raw source.",
     "@wubustreams boots up; the meme transcript begins."),
    ("An encryption key is made", "digital", "cuda", "all", True,
     "Trust manufactured daily in math; the constant you can't see.",
     "Your TLS session spun up before the first frame."),
    ("A cache is invalidated", "digital", "cuda", "all", True,
     "The daily forgetting of machines; stale data purged on schedule.",
     "The CDN drops old clips; only the new survive."),
    ("A backup is written", "digital", "cuda", "all", True,
     "The species now copies its memory daily; redundancy as ritual.",
     "Your VOD lands in cold storage; the fossil preserved."),
    ("A feed is ranked", "digital", "internet", "all", True,
     "An algorithm decides what you see every refresh; the daily curate.",
     "Chat clips surface because the ranker liked them."),
    ("A cookie is dropped", "digital", "internet", "all", True,
     "The tracking crumb; identity leased to the ad network daily.",
     "You accept all, the profile thickens, the price shifts."),

    # ---- ECONOMIC / MECHANICAL (DC076-DC090) ----
    ("Markets open and close", "mechanical", "penny", "daily_life", True,
     "A timezone cascade of trading; the global pulse, 24/5.",
     "Tokyo opens while you sleep, NY closes as you stream."),
    ("A factory produces", "mechanical", "cuda", "all", True,
     "The daily output of things; the physical internet of goods.",
     "A console rolls off a line; it'll be in your hands in weeks."),
    ("A truck delivers", "mechanical", "versa", "drive_commute", True,
     "The daily resupply; the road is a conveyor belt with drivers.",
     "A semi passes you, same lane, different cargo, same grind."),
    ("Lights turn on at dusk", "mechanical", "supercap", "daily_life", True,
     "The daily artificial dawn; the grid answers the sunset.",
     "The porch light clicks on, timer, no thought given."),
    ("An engine ignites", "mechanical", "supercap", "drive_commute", True,
     "Combustion on demand; the daily promise of movement.",
     "The Versa turns over at 7am, the day's first fire."),
    ("A battery charges", "mechanical", "supercap", "all", True,
     "The daily drinking of stored sun; the supercap dream, approximated.",
     "Controller on the dock, filling, ready for tonight."),
    ("An ATM dispenses", "mechanical", "penny", "daily_life", True,
     "Cash summoned from the wall; the magic window of the economy.",
     "You pull $40 for gas; the machine never sleeps."),
    ("Crops are harvested", "mechanical", "paulsen", "daily_life", True,
     "The daily reaping; sunlight banked as food, on schedule.",
     "A field machines through at dawn; your cereal started there."),
    ("Trash is collected", "mechanical", "versa", "daily_life", True,
     "The daily erasure; civilization is mostly logistics of disposal.",
     "The bin rolls to the curb; the stream of waste flows on."),
    ("The power grid balances", "mechanical", "supercap", "all", True,
     "Supply meets demand every second; the invisible daily tightrope.",
     "The grid holds your rig at 700W while you push frames."),
    ("A train departs", "mechanical", "versa", "drive_commute", True,
     "The steel commute; the older, calmer cousin of your drive.",
     "A freight leaves the yard as you merge onto the highway."),
    ("A ship docks", "mechanical", "versa", "all", True,
     "The daily port choreography; 80% of goods arrive by sea.",
     "A container ship ties up; its box may hold your next mic."),
    ("A plane lands", "mechanical", "versa", "all", True,
     "~200,000 flights/day; the daily defiance of gravity, normalized.",
     "A jet banks over your roof; you don't look up anymore."),
    ("A coin jingles", "mechanical", "penny", "all", True,
     "The sound of loose value; the penny motif's daily trigger.",
     "Change in the cup holder, the Versa's percussion section."),
    ("A traffic light cycles", "mechanical", "versa", "drive_commute", True,
     "The daily red/green liturgy; patience enforced by timer.",
     "You stop at the same light every morning, same 90 seconds."),

    # ---- PSYCHOLOGICAL / ABSTRACT (DC091-DC100) ----
    ("Attention shifts", "psyche", "cuda", "all", True,
     "~3-5 focus shifts/min; the mind is a restless spotlight.",
     "You snap from game to chat to Discord, never still."),
    ("A memory forms", "psyche", "meme", "all", True,
     "The day is archived continuously; most of it is overwritten by tonight.",
     "You'll remember this clutch, forget the loading screens."),
    ("A memory is forgotten", "psyche", "meme", "all", True,
     "Forgetting is the daily edit; the brain curates by deletion.",
     "You can't recall yesterday's stream; only the clip survives."),
    ("A worry arises", "psyche", "meme", "night_think", True,
     "The threat-simulator runs unprompted; anxiety is a default app.",
     "2am: the commute cost, the bills, the 'am I behind' loop."),
    ("A plan is made", "psyche", "meme", "all", True,
     "The future is drafted daily; most plans are rough cuts.",
     "You map tomorrow's stream in your head on the drive home."),
    ("Boredom visits", "psyche", "meme", "all", True,
     "The itch that drives creation; boredom is the mother of content.",
     "Queue time, you open the editor, something gets made."),
    ("A song gets stuck", "psyche", "meme", "gaming_stream", True,
     "The earworm; a meme that hijacks the auditory cortex.",
     "The stream's intro theme, looping, you hum it offline."),
    ("Deja vu flickers", "psyche", "meme", "all", True,
     "The brain's glitch of recognition; the daily ghost in the machine.",
     "A moment in the game feels exactly like a dream you had."),
    ("A small hope appears", "psyche", "meme", "all", True,
     "The daily optimism reflex; the species bets on tomorrow by default.",
     "You queue ranked believing this is the climb game."),
    ("A penny is found heads-up", "psyche", "penny", "all", True,
     "The motif's daily invocation; loose change as inherited meaning.",
     "On the sidewalk, tails-or-heads, you read it as a sign anyway."),
]

# 4 voice modes to de-bore the instance lines across 100 constants.
# Mode 0: first-person stream moment (yours)
# Mode 1: observer / anthropological (the species)
# Mode 2: dry speculist / TDA verdict style
# Mode 3: cosmic / scale joke
VOICE_TAILS = [
    None,  # keep base instance as-is (yours)
    " The species does this without consent and calls it a Tuesday.",
    " TDA verdict: real, recurring, and nobody logs it. That's the point.",
    " At civilizational scale this is a rounding error; at yours it's the whole day.",
]

def build():
    constants = []
    for i, (name, cat, theme, stream, univ, overlap, inst) in enumerate(BASE, 1):
        # vary the instance voice so 100 pages don't read like one template
        tail = VOICE_TAILS[i % len(VOICE_TAILS)]
        if tail and (not univ or i % 7 == 0):
            inst = inst + tail
        # varied overlap thread line so the calendar/constants volume isn't one template
        THREADS = [
            f"THREAD {i:03d} &rarr; your streams mutate this daily. universal={str(univ).lower()}",
            f"THREAD {i:03d} &rarr; overlaps @wubustreams when you're live. universal={str(univ).lower()}",
            f"THREAD {i:03d} &rarr; the constant under your commute. universal={str(univ).lower()}",
            f"THREAD {i:03d} &rarr; Cambrian overlap: this + your night-think. universal={str(univ).lower()}",
        ]
        thread = THREADS[i % len(THREADS)]
        constants.append({
            "id": f"DC{i:03d}",
            "name": name,
            "category": cat,
            "theme": theme,
            "stream_link": stream,
            "universal": univ,
            "overlap": overlap,
            "instance": inst,
            "thread": thread,
            "rotation_index": i,  # for pick_svg rotation in the builder
        })
    meta = {
        "project": "Seymour Wins — Daily Constants",
        "purpose": ("100 things that happen every day, everywhere. Structural substrate "
                    "for the memetic-overlap timeline. Each constant is a vertical thread; "
                    "the user's stream transcripts (@wubustreams) overlap onto them — the "
                    "Cambrian explosion of memetic overlap information."),
        "count": len(constants),
        "themes": sorted({c["theme"] for c in constants}),
        "stream_links": sorted({c["stream_link"] for c in constants}),
        "categories": sorted({c["category"] for c in constants}),
        "usage": ("organize_constants.py --match '<transcript>' tags a stream moment to "
                  "constants; --stream gaming_stream emits overlap entries for the calendar."),
    }
    doc = {"meta": meta, "constants": constants}
    with open(OUT, "w") as f:
        json.dump(doc, f, indent=2)
    print(f"WROTE {OUT}: {len(constants)} constants")
    # quick distribution report
    from collections import Counter
    print("by category:", dict(Counter(c["category"] for c in constants)))
    print("by theme:", dict(Counter(c["theme"] for c in constants)))
    print("by stream_link:", dict(Counter(c["stream_link"] for c in constants)))

if __name__ == "__main__":
    build()
